name: Update Hugging Face Space content

on:
  repository_dispatch:
    types: [update-roles-json]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install -U huggingface_hub

      - name: Login to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: huggingface-cli login --token "$HF_TOKEN"

      - name: Clone Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          huggingface-cli repo clone wan-yun/simulated-patient-gguf-v2 --type=space space-dir

      - name: Update roles.json if changed
        run: |
          cp roles.json space-dir/roles.json || true
          cd space-dir
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add roles.json || true

      - name: Commit and Push
        run: |
          cd space-dir
          git commit -m "🤖 Auto update roles.json via webhook" || echo "Nothing to commit"
          git push
